### ISSUE TITLE
Easy One? Add Days of the Week to the schedule

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/SciPy-2014#139]
That is, I got an email from a brilliant attendee requesting that, instead of dates like "July 8, 2014", the conference schedule might be more human readable if it had the day of the week. 

That is, can we change the schedule page to have entries such as : "Tuesday July 8, 2014" or "Tuesday July 8" even just "Tuesday"? I think it'll help folks keep track of what day is which. 

I grepped and grepped, but I can't see where this change needs to be made (maybe it's in the database somewhere?). If I can help, just let me know where I need to make this change.

**Comment by codersquid** [comment]
I closed this prematurely. What do you think of something like "Sunday, July 6"? I've got that rendering on the full schedule right now.

No apologies necessary. It's not obvious to see where the information comes from because it was in the symposion repo.  Here's a recap of the change: I copied [schedule_conference.html](https://github.com/pinax/symposion/blob/master/symposion/templates/schedule/schedule_conference.html) to our repo and changed line [29](https://github.com/scipy-conference/SciPy-2014/blob/master/scipy2014/templates/schedule/schedule_conference.html#L29) to change the date format.

I notice that it doesn't change how the date is rendered on individual pages. Do you want that?

**Comment by katyhuff** [comment]
Looks great! Thanks for the explanation! No need to worry about the individual pages.
Thanks!!! :+1:
