### ISSUE TITLE
fix topic track

### ISSUE THREAD

**Issue by mrterry** [scipy-conference/SciPy-2014#15]
the topic tracks are from last year.  update them. @aterrel what are our tracks this year?

**Comment by katyhuff** [comment]
The topics this year are "Scientific Computing Education" and GIS... The appropriate formal title of the GIS track isn't abundantly clear to me. I think @sjsrey would know exactly what to call it. "Geographical Information Systems"? "Geospatial Data"? "Geospatial Science"? "Geospatial Data and Science?"

**Comment by aterrel** [comment]
I vote for Geospatial Data

**Comment by mandli** [comment]
I second "Geospatial Data in Science", I think leaving it broad like that
will encompass a lot more people rather than pegging it to GIS.  Myself I
would at least look through the talks if the topic was titled "Geospatial
Data in Science" where as GIS would probably scare me off a bit.

**Comment by sjsrey** [comment]
All good points thus far. One possible consideration is that GIS could be
taken to be "Geographic Information Science" rather than "Geographic
Information Systems".

## 

Sergio (Serge) Rey
Professor, School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
Arizona State University
http://geoplan.asu.edu/rey

Editor, International Regional Science Review
http://irx.sagepub.com

**Comment by kthyng** [comment]
I personally would just assume that is what GIS stands for.

On Mon, Jan 6, 2014 at 3:07 PM, Sergio Rey notifications@github.com wrote:

> All good points thus far. One possible consideration is that GIS could be
> taken to be "Geographic Information Science" rather than "Geographic
> Information Systems".
> 
> ## 
> 
> Sergio (Serge) Rey
> Professor, School of Geographical Sciences and Urban Planning
> GeoDa Center for Geospatial Analysis and Computation
> Arizona State University
> http://geoplan.asu.edu/rey
> 
> Editor, International Regional Science Review
> http://irx.sagepub.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/15#issuecomment-31687082
> .

## 

Kristen M. Thyng
Postdoctoral Research Associate
Department of Oceanography
Texas A&M University
http://kristenthyng.com

**Comment by katyhuff** [comment]
Let's go with "Geographic Information Science" then!

**Comment by kthyng** [comment]
Oops, sorry, what I meant to imply is that for people who don't do GIS, but
do do work involving geographical data and science, anything with "GIS" or
G\* I\* S\* will imply something other than just work involving geographical
data and science. My understanding is that this is meant to be a superset
of these two things (GIS-specifically, and the science-with-geography
side), in which case the more general name of Geospatial Data in Science
would be better since it doesn't have the GIS-specific connotation.

On Mon, Jan 6, 2014 at 4:43 PM, Katy Huff notifications@github.com wrote:

> Let's go with "Geographic Information Science" then!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/15#issuecomment-31695499
> .

## 

Kristen M. Thyng
Postdoctoral Research Associate
Department of Oceanography
Texas A&M University
http://kristenthyng.com

**Comment by katyhuff** [comment]
Ah, I see. Yes, I misunderstood, thinking you meant the opposite. Geospatial Data in Science, then? :)

**Comment by kthyng** [comment]
That works for me!

On Mon, Jan 6, 2014 at 4:51 PM, Katy Huff notifications@github.com wrote:

> Ah, I see. Yes, I misunderstood, thinking you meant the opposite.
> Geospatial Data in Science, then? :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scipy-conference/SciPy-2014/issues/15#issuecomment-31696169
> .

## 

Kristen M. Thyng
Postdoctoral Research Associate
Department of Oceanography
Texas A&M University
http://kristenthyng.com
