### ISSUE TITLE
Create mock schedule in staging

### ISSUE THREAD

**Issue by aterrel** [scipy-conference/SciPy-2014#68]
Create some fake data and have a mock schedule for when we get the production ready version.

**Comment by codersquid** [comment]
I should leave a status here. I ran in to some questions and posted to the symposion mailing list.

https://groups.google.com/forum/#!msg/pinax-symposion/Irv4kMYY8zk/5uoemo53iZsJ

excerpt

> Here is a fake site I set up for testing. https://citationsneeded.org/scipy2014/schedule/. I have some fake talks that I've marked accepted, and I've used the django admin to assign them to talks. I do not see them in the schedule. I used the django admin to create slots, assign presentations to slots, etc.
> - Do tracks correspond to Slot Kinds?
> - How do I get talks to show up in the schedule?
> - Are there schedule edit pages I can use rather than the django admin?
> - Are there any django commands I should be using?

(I'm hoping there are commands that speed up the process and that people do not need to use the django admin for it).

**Comment by codersquid** [comment]
![sched](https://f.cloud.github.com/assets/529748/2352148/9e3bc848-a585-11e3-8ba0-48884059895c.png)

(here is a screenshot of the fake sched)

**Comment by katyhuff** [comment]
Here's the real schedule: https://docs.google.com/spreadsheet/ccc?key=0AiP1TmlNKprrdGE1aWV0dGNDMnlCSl9KSTFSX2Nib2c&usp=drive_web#gid=0

Let me know if you can't get access to it.

**Comment by katyhuff** [comment]
(on second thought, maybe you were already looking at it.... if so, sorry for stating the obvious... but, if you hadn't seen it, it exists).

**Comment by codersquid** [comment]
There's an incoming PR to the sympsion project with some docs about working with the schedule app. This is useful! https://github.com/pinax/symposion/pull/51

**Comment by aterrel** [comment]
@codersquid cool should we start use master for symposion to get this?

**Comment by codersquid** [comment]
@aterrel I think it depends on if the PR gets in to master. We could look at using the pyohio fork if not.

**Comment by aterrel** [comment]
Okay I'll wait for your advice on the matter.

**Comment by codersquid** [comment]
This has been a huge pain. Here are my current notes (I've got running commentary in the wiki scratchpad) but will share them here:

I spent time merging the pyohio pull request with the schedule builder in to our symposion fork (you can't just merge that pull request, you need to pick up some other changes from the pyohio fork -- and then edit them since vanilla symposion doesn't work with django > 1.4 and when we started the scipy conf app we based it off vanilla symposion -- I do not recommend this for next year).

Now that I have that merged. I'm working on figuring out exactly which columns in the csv file correspond to which models so that I can be sure to have enough data in the database for the csv file to be consumed. right now I'm getting some key errors. btw, working out what you need to have to exist for a presentation to exist is painful with no documentation. here is a picture.

```
  model dependencies                                     
+----->section   (conference app)                        
|         ^                                              
|         |                                              
|         +                                              
|      schedule   (schedule app)                         
|         ^                                              
|         |                                              
|         |                                              
|    +----+----+----+                                    
|    +         +    +                                    
|  slotkind   day   room                                 
|     ^        ^     ^                                   
|     +--------+     |        proposalbase (proposal app)
|     +              +           ^                       
|    slot           slotroom     |                       
|     ^                          |                       
|     |                          |                       
|     +                          |                       
+-+presentation+-----------------+                       
```

Ps. I'd really love to be able to see the pull requests in the symposion repo get reviewed and hopefully accepted. Is there any way we can help with that?

**Comment by codersquid** [comment]
Oh, and here is the stack trace I get when trying to parse my example csv. It's probably something I'll figure out quickly, but I just realized I should document the progress so that we know where the hitches were so that we know what we should document. If I'm not allowed to at least get a documentation pull request accepted to symposion I am going to HULK SMASH.

```
Traceback:
File "/home/sheila/.virtualenvs/scipy2014/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                         response = callback(request, *callback_args, **callback_kwargs)
File "/home/sheila/.virtualenvs/scipy2014/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/home/sheila/.virtualenvs/scipy2014/src/symposion/symposion/schedule/views.py" in schedule_edit
  110.                 msg = form.build_schedule()
File "/home/sheila/.virtualenvs/scipy2014/src/symposion/symposion/schedule/forms.py" in build_schedule
  122.         created_items.extend(self._build_rooms(data))
File "/home/sheila/.virtualenvs/scipy2014/src/symposion/symposion/schedule/forms.py" in _build_rooms
  91.         rooms = sorted(set([x[self.ROOM_KEY] for x in data]))

Exception Type: KeyError at /scipy2014/schedule/talks-posters/edit/
Exception Value: 'room'
```

**Comment by codersquid** [comment]
I've had this sorted out for a while. Sorry for not closing it sooner! You can see how to make a schedule from #132
